### ISSUE TITLE
Issue when using constructor

### ISSUE THREAD

**Issue by luismendes535** [feonit/olap-cube-js#1]
Hey feonit,

I'm having a problem when trying to run the following line 
`let cube = new Cube(facts, schema);`

I get this error: 
> ReferenceError: Cube is not defined

Can you tell me how it's supposed to import your library?

Thanks in advance.

**Comment by feonit** [comment]
Hello Luis, you are the first one from whom I received feedback, it's nice, thank you.
For versions before `<0.4.0` you need to add like this:
`let cube = new Cube(facts, schema).default;`

Beginning with `>=0.4.0` now it should work:
`let cube = new Cube(facts, schema);`

Please inform if the problem was solved

**Comment by luismendes535** [comment]
It's working correctly in the version 0.4.0.

I had to change it manually in the package.json from 0.3.0 to 0.4.0. 

PS: Version 0.3.0 didn't work for me with your solution though.

Thank you feonit!

**Comment by feonit** [comment]
I'm sorry, I meant like this (for 0.3.0):
`const cube = new Cube.default(facts, schema)`
