### ISSUE TITLE
Does it support date/time dimension?

### ISSUE THREAD

**Issue by kstan79** [feonit/olap-cube-js#3]
Hi,

Can I know this library support date/time dimension? Example I have document_date (YYYY-MM-DD), will it able to help us break into Year, Month, Period, Quarterly, Daily dimension? If yes how to do with this library?

Thanks,
Ks Tan

**Comment by feonit** [comment]
Hello
This library does not have the functionality to work with data of type Date or Time. Values of attributes for dimension tables can only be a string or number (it is in this type that it is expected that JSON data will be passed).
Thanks for the question, I'll try in the future to explore the possible need for such functionality in this library
I would in your place write the function adapter, which would functionally do the following:
```js
let facts = [{ document_day: "2018-07-26" } /** ... */ ];
facts = facts.map(({ document_date, ...rest }) => {
    let date = new Date(document_date)
    return { 
       document_year:  date.getFullYear(),
       document_month:  date.getMonth(),
       /** ... other parts of data for last dimensions based on date data */
      ...rest
    }
}) 

let dimensionHierarchies = [
  {
    dimensionTable: { 
      dimension: ‘month’, 
      keyProps: [‘document_month’] 
    },
    level: [
      {
         dimensionTable: { 
           dimension: ‘year’, 
           keyProps: [‘document_year’] 
        },
        level: [
	  /** ... */
        ]
      }
    ]
  }
]
```

Hierarchy of Date must be in next order:  Year => Month => Quarterly => Daily
For Period here no place because multiple hierarchy right now not supported. In feature i try do hierarchy like this:

```
Year => Quarterly => Month => Daily
      \\             //
        CustomPeriod
```

**Comment by kstan79** [comment]
cool, thanks reply.
